routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin/dashboard',function(){
return view('admin.dashboard');
});
Route::get('/user/dashboard','PostController@userDashboard');
Route::resource('tag','TagController');
Route::resource('post','PostController');
Route::get('/delete/post/tag/{postId}/{tagId}','PostController@deletePostTag');
Route::get('/tag/posts/{tagId}','PostController@postsWithTag');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title','description','avatar'];
    
    public function tags()
    {
    	return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use Session;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('admin.post.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags=Tag::all();
        return view('admin.post.create',compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
         'title' => 'required',
         'description' => 'required',
         'avatar' => 'required'
        ]);
        if($request->file('avatar'))
        {
            $avatar = $request->file('avatar');
            $filename = time() . '.' . $avatar->getClientOriginalExtension();
            $request->file('avatar')->move('avatars',$filename);
          
        }else{
            $filename='';
        }
        $post=Post::create([
            'title'      =>$request->title,
            'description'=>$request->description,
            'avatar'     =>$filename,

        ]);
        if(count($request->tags)){
            foreach ($request->tags as $key => $tag) {
                #if tag has no value
                if($tag !=null)
                if(in_array($tag,$post->tags()->pluck('tag_id')->toArray())==false){
                    #if tag is not already exist
                    $post->tags()->attach($tag);
                }
            }
        }
        Session::flash('success','Post has been successfully added.');
        return redirect('/post');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('admin.post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if($id){
            $post = Post::findOrFail($id);
            $tags = Tag::all();
            return view('admin.post.edit',compact('post','tags'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        if($request->file('avatar')){
            $avatar = $request->file('avatar');
            #name the image with time and extention 
            $filename = time() . '.' . $avatar->getClientOriginalExtension();
            $request->file('avatar')->move('avatars',$filename);
            $post->avatar = $filename;
        }
        if($post){
            $post->title = $request->title;
            $post->description = $request->description;
        }
        $post->save();
        if(count($request->newTags)){
            foreach ($request->newTags as $key => $tag) {
                if($tag !=null)#if tag is empty or has no value
                if(in_array($tag,$post->tags()->pluck('tag_id')->toArray())==false){#if tag is not already exist
                    $post->tags()->attach($tag);
                }
            }
        }
        Session::flash('success','This post has successfully updated.');
        return redirect('/post');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findorfail($id)->delete();
        Session::flash('success','This post has successfully deleted.');
        return redirect()->back();
    }

    public function deletePostTag($postId,$tagId)
    {
        $post = Post::findOrFail($postId);
        #remove all relationship value
        $post->tags()->detach($tagId);
        Session::flash('success','This post tag has successfully deleted.');
        return redirect()->back();
    }

    public function postsWithTag($tagId)
    {
        $tag = Tag::findOrFail($tagId);
        $posts = $tag->posts;
        return view('user.all-posts',compact('posts'));
    }
    public function userDashboard()
    {
        $posts = Post::all();
        return view('user.dashboard',compact('posts'));  
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>Add A Post</h1>
	</div>
	<div class="col-md-6">
		<form method="post" action="{{route('post.store')}}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="col-md-12">
				<label>Post Title</label>
				<input type="text" name="title" class="form-control" required="ture">
			</div>
			<div class="col-md-12">
				<label>Post Description</label>
				<textarea name="description" class="form-control" cols="10" rows="10"></textarea>
			</div>
			<div class="col-md-12">
				<label>Post Image</label>
				<input type="file" name="avatar" class="form-control" required="ture">
			</div>
			<div class="col-md-12 ">
				<label>Add Tags</label>
				<div class="tags">
					<select name="tags[]" class="form-control">
					<option value="">select</option>
					@foreach($tags as $tag)
					<option value="{{$tag->id}}">{{$tag->tag}}</option>
					@endforeach
				</select>
				</div>
				<br>
				<a href="javascript:void(0)" onclick="addTag()" class="btn btn-primary">Add Tag</a>
				
				
			</div>
			<div class="col-md-12">
				<br>
				<input type="submit" value="ADD POST" class="btn btn-success" class="pull-right" >
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	function addTag()
	{
		$('.tags').append('<select name="tags[]" class="form-control"><option>select</option>@foreach($tags as $tag)<option value="{{$tag->id}}">{{$tag->tag}}</option>@endforeach</select>');
	}
</script>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>Update A Post</h1>
	</div>
	<div class="col-md-6">
		<form method="post" action="{{url('post/'.$post->id)}}" enctype="multipart/form-data">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			<div class="col-md-12">
				<label>Post Title</label>
				<input type="text" name="title" class="form-control" value="{{$post->title}}">
			</div>
			<div class="col-md-12">
				<label>Post Description</label>
				<textarea name="description" class="form-control" cols="10" rows="10">{{$post->description}}</textarea>
			</div>
			<div class="col-md-12">
				<label>Post Image</label>
				<img width="200" src="{{asset('avatars/'.$post->avatar)}}">
			</div>
			<div class="col-md-12" id="newImage">
				<label>Post New Image</label>
				<input type="file" name="avatar" class="form-control" >
			</div>
			<div class="col-md-12 ">
				<label>	Post Tags</label>
				<div class="tags">
					<table id="tag">
						<tr>
							<th>Tags</th>
							<th>Action</th>
						</tr>
						@foreach($post->tags as $tag)
                         <tr>
							<td>{{$tag->tag}}</td>
							<td>
								<a href="{{url('/delete/post/tag/'.$post->id.'/'.$tag->id)}}" class="btn btn-danger">Delete</a>
							</td>
						</tr>
						@endforeach
					</table>
					
				</div>
				<br>
				<a href="javascript:void(0)" onclick="addTag()" class="btn btn-primary">Add Tag</a>
				
				
			</div>
			<div class="col-md-12">
				<br>
				<input type="submit" value="UPDATE POST" class="btn btn-success" class="pull-right" >
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	$('#newImage').hide();
	function addTag()
	{
		$('.tags').append('<select name="newTags[]" class="form-control"><option>select</option>@foreach($tags as $tag)<option value="{{$tag->id}}">{{$tag->tag}}</option>@endforeach</select>');
	}
</script>
@endsection

resources/views/admin/post/index.blade.php
@extends('admin.partial.master')
@section('content')
<div class="col-md-12">
	<h1>All Posts</h1>
	<table id="tag">
		<tr>
			<th>Sr.</th>
			<th>Title</th>
			<th>Image</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		@if(count($posts))
			@foreach($posts as $key=>$post)
			<tr>
				<td>{{$key +1}}</td>
				<td>{{$post->title}}</td>
				<td><img src="{{asset('avatars/'.$post->avatar)}}" class="postImage"></td>
				<td><a href="{{url('/post/'.$post->id)}}">Show</a></td>
				<td><a href="{{url('/post/'.$post->id.'/edit')}}">Edit</a></td>
				<td>
					<form method="post" action="{{url('post/'.$post->id)}}">
						{{ csrf_field() }}
				        {{ method_field('DELETE') }}
						<input type="submit" value="Delete">
					</form>
			</tr>
			@endforeach
		@else
		<p>There is no post.</p>	
		@endif	
	</table>
</div>
@endsection

resources/views/admin/post/show.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>A Post Detail</h1>
	</div>
	<div class="col-md-6">
			<div class="col-md-12">
				<label>Post Title</label>
				<input type="text" name="title" class="form-control" value="{{$post->title}}" readonly="ture">
			</div>
			<div class="col-md-12">
				<label>Post Description</label>
				<textarea name="description" class="form-control" cols="10" rows="10" readonly="ture">{{$post->description}}</textarea>
			</div>
			<div class="col-md-12">
				<label>Post Image</label>
				<img width="200" src="{{asset('avatars/'.$post->avatar)}}">
			</div>
			<div class="col-md-12 ">
				<label>	Post Tags</label>
				<div class="tags">
					@foreach($post->tags as $tag)
                        <p class="tagedit">{{$tag->tag}}</p>
					@endforeach
				</div>
			</div>
			<div class="col-md-12">
				<br>
				<a href="{{ URL::previous() }}" class="btn btn-success">Back</a>
			</div>
		</form>
	</div>
</div>
@endsection