routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin/dashboard',function(){
return view('admin.dashboard');
});
Route::get('/user/dashboard','PostController@userDashboard');
Route::resource('tag','TagController');
Route::resource('post','PostController');
Route::get('/delete/post/tag/{postId}/{tagId}','PostController@deletePostTag');
Route::get('/tag/posts/{tagId}','PostController@postsWithTag');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable=['tag'];

    public function posts()
    {
    	return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Tag;
use Session;
class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
        'tag' => 'required',
         ]);
        if(Tag::where('tag',$request->tag)->first()){
            Session::flash('danger','This tag already exist please add a diffirent tag.');
            return redirect()->back();
        }
        Tag::create(['tag'=>$request->tag]);
        Session::flash('success','This tag has successfully added.');
        return redirect('/tag');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tag = Tag::findOrFail($id);
        return view('admin.tag.show',compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::findOrFail($id);
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::where('id',$id)->update(['tag'=>$request->tag]);
        Session::flash('success','This tag has successfully updated.');
        return redirect()->back();
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::findOrFail($id)->delete();
        Session::flash('success','This tag has successfully deleted.');
        return redirect()->back();
    }
}

resources/views/admin/tag/create.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>Add A Tag</h1>
	</div>
	<div class="col-md-6">
		<form method="post" action="{{route('tag.store')}}">
			{{ csrf_field() }}
			<div class="col-md-12">
				<label>Tag Name</label>
				<input type="text" name="tag" class="form-control" required="ture">
			</div>
			<div class="col-md-12">
				<br>
				<input type="submit" value="ADD" class="btn btn-success" class="pull-right" >
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>Update A Tag</h1>
	</div>
	<div class="col-md-6">
		<form method="post" action="{{url('tag/'.$tag->id)}}">
			{{ csrf_field() }}
			{{ method_field('PUT') }}
			<div class="col-md-12">
				<label>Tag Nmae</label>
                <input type="test" name="tag" class="form-control" value="{{$tag->tag}}" required="ture">
			</div>
			<div class="col-md-12">
				<br>
				<input type="submit" value="UPDATE" class="btn btn-success" class="pull-right" >
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('admin.partial.master')
@section('content')
<div class="col-md-12">
	<table id="tag">
		<tr>
			<th>Sr.</th>
			<th>Tag</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		@if(count($tags))
			@foreach($tags as $key=>$tag)
			<tr>
				<td>{{$key +1}}</td>
				<td>{{$tag->tag}}</td>
				<td><a href="{{url('/tag/'.$tag->id)}}">Show</a></td>
				<td><a href="{{url('/tag/'.$tag->id.'/edit')}}">Edit</a></td>
				<td>
					<form method="post" action="{{url('tag/'.$tag->id)}}">
						{{ csrf_field() }}
				        {{ method_field('DELETE') }}
						<input type="submit" value="Delete">
					</form>
			</tr>
			@endforeach
		@else
		   <p>There is no tag.</p>
		@endif	
	</table>
</div>
@endsection

resources/views/admin/tag/show.blade.php
@extends('admin.partial.master')
@section('content')
<div class="row custom_row">
	<div class="col-md-12">
		<h1>Tag</h1>
	</div>
	<div class="col-md-6">
		<div class="col-md-12">
			<label>Tag Nmae</label>
            <input type="test" name="tag" class="form-control" value="{{$tag->tag}}" readonly="ture">
		</div>
		<div class="col-md-12">
			<br>
			<a href="{{ URL::previous() }}" class="btn btn-success">Back</a>
		</div>
	</div>
</div>
@endsection